name: generate animation

on:
  # 每 24 小时自动运行一次
  schedule:
    - cron: "0 */24 * * *"

  # 允许随时手动运行工作流
  workflow_dispatch:

  # 在 master 分支上的每次推送时运行
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 生成一个 GitHub 用户 (<github_user_name>) 的贡献图蛇形游戏，并输出为 svg 动画文件
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 将 <build_dir> 的内容推送到目标分支
      # 内容将可通过以下 URL 访问：
      # https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> 或作为 GitHub 页面
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
